# Generated by Django 3.2.25 on 2025-09-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(max_length=200)),
                ('paciente_dni', models.CharField(blank=True, max_length=20, null=True)),
                ('paciente_edad', models.PositiveIntegerField(blank=True, null=True)),
                ('paciente_direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('paciente_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('obra_social', models.CharField(blank=True, max_length=100, null=True)),
                ('medico', models.CharField(blank=True, max_length=200, null=True)),
                ('diagnostico', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('concretado', 'Concretado'), ('no_concretado', 'No Concretado')], default='pendiente', max_length=20)),
                ('motivo_no_concretado', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresupuestoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.prestacion')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='presupuestos.presupuesto')),
            ],
        ),
    ]
