# Generated by Django 3.2.25 on 2025-10-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_auto_20250930_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='paciente_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
