# Generated by Django 3.2.25 on 2025-10-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_presupuesto_paciente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestacion',
            name='precio',
        ),
        migrations.AddField(
            model_name='prestacion',
            name='especialista',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestacion',
            name='gastos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='tipo',
            field=models.CharField(choices=[('gastos', 'Gastos'), ('especialista', 'Especialista'), ('otro', 'Otro')], default='gastos', max_length=20),
        ),
    ]
