# Generated by Django 3.2.25 on 2025-10-03 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_auto_20251002_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestoitem',
            name='tipo',
            field=models.CharField(choices=[('gastos', 'Gastos'), ('especialista', 'Especialista'), ('todo', 'Todo')], default='gastos', max_length=20),
        ),
        migrations.CreateModel(
            name='PresupuestoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('datos', models.JSONField()),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='presupuestos.presupuesto')),
            ],
        ),
    ]
