# Generated by Django 3.2.25 on 2025-10-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0008_auto_20251014_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='prestacion',
            name='tipo',
            field=models.CharField(choices=[('particular', 'Particular'), ('ips', 'IPS')], default='obra_social', max_length=50),
        ),
    ]
