# Generated by Django 3.2.25 on 2025-10-17 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0009_auto_20251016_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='obra_social',
            field=models.ForeignKey(default=92, on_delete=django.db.models.deletion.CASCADE, related_name='obras_sociales', to='presupuestos.obrasocial'),
            preserve_default=False,
        ),
    ]
