# Generated by Django 3.2.25 on 2025-10-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0010_alter_presupuesto_obra_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='fecha_creacion',
            field=models.DateTimeField(),
        ),
    ]
