# Generated by Django 3.2.25 on 2025-10-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0011_alter_presupuesto_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestoitem',
            name='comentario',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='medio_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('cajab', 'Caja B'), ('transferencia', 'Transferencia'), ('tarjeta_credito', 'Tarjeta Credito'), ('tarjeta_debito', 'Tarjeta Debito')], max_length=50),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('en_curso', 'En curso'), ('cerrado', 'Cerrado'), ('expirado', 'Expirado'), ('anulado', 'Anulado')], default='pendiente', max_length=20),
        ),
    ]
