# Generated by Django 3.2.25 on 2025-11-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0012_auto_20251023_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocial',
            name='porcentaje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
