# Generated by Django 3.2.25 on 2026-03-13 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presupuestos', '0013_obrasocial_porcentaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reintegro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('cajab', 'Caja B'), ('transferencia', 'Transferencia'), ('tarjeta_credito', 'Tarjeta Credito'), ('tarjeta_debito', 'Tarjeta Debito')], max_length=50)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reintegros', to='presupuestos.presupuesto')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reintegro_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reintegro_user_made', to=settings.AUTH_USER_MODEL, verbose_name='hecho por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reintegro_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
