# Generated by Django 3.2.25 on 2026-03-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0014_reintegro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reintegro',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
