# Generated by Django 3.2.25 on 2026-03-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0015_alter_reintegro_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_fin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_inicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='hc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
