# Generated by Django 3.2.25 on 2026-03-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0016_auto_20260317_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacion',
            name='categoria',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
