# Generated by Django 3.2.25 on 2026-03-27 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presupuestos', '0017_prestacion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestoitem',
            name='fecha_liquidacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='liquidado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='liquidado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='liquidado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_liquidados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='observaciones_liquidacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
