# Generated by Django 3.2.25 on 2025-05-20 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklocal',
            name='user_deleted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocklocal_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por'),
        ),
        migrations.AddField(
            model_name='stocklocal',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocklocal_user_made', to=settings.AUTH_USER_MODEL, verbose_name='echo por'),
        ),
        migrations.AddField(
            model_name='stocklocal',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocklocal_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.categoria', verbose_name='Categoría del producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='user_deleted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producto_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por'),
        ),
        migrations.AddField(
            model_name='producto',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producto_user_made', to=settings.AUTH_USER_MODEL, verbose_name='echo por'),
        ),
        migrations.AddField(
            model_name='producto',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producto_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.ingresolote'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='user_deleted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientostock_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientostock_user_made', to=settings.AUTH_USER_MODEL, verbose_name='echo por'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientostock_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddField(
            model_name='local',
            name='user_deleted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por'),
        ),
        migrations.AddField(
            model_name='local',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_user_made', to=settings.AUTH_USER_MODEL, verbose_name='echo por'),
        ),
        migrations.AddField(
            model_name='local',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddField(
            model_name='ingresolote',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.local'),
        ),
        migrations.AddField(
            model_name='ingresolote',
            name='user_deleted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingresolote_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por'),
        ),
        migrations.AddField(
            model_name='ingresolote',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingresolote_user_made', to=settings.AUTH_USER_MODEL, verbose_name='echo por'),
        ),
        migrations.AddField(
            model_name='ingresolote',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingresolote_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='user_deleted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoria_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoria_user_made', to=settings.AUTH_USER_MODEL, verbose_name='echo por'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoria_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AlterUniqueTogether(
            name='stocklocal',
            unique_together={('producto', 'local')},
        ),
    ]
