# Generated by Django 3.2.25 on 2025-05-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklocal',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
