# Generated by Django 3.2.25 on 2025-06-21 16:10

import applications.core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_stocklocal_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.ImageField(blank=True, null=True, storage=applications.core.storages.MediaLocalStorage(), upload_to='barcodes/'),
        ),
    ]
