# Generated by Django 3.2.25 on 2025-06-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
