# Generated by Django 3.2.25 on 2025-06-23 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20250621_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='gramos',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto'),
        ),
    ]
