# Generated by Django 3.2.25 on 2025-06-30 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='user_deleted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminal_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminal_user_made', to=settings.AUTH_USER_MODEL, verbose_name='hecho por'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminal_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddField(
            model_name='movimientocomponente',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.componente'),
        ),
        migrations.AddField(
            model_name='movimientocomponente',
            name='destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destino_componente', to='inventario.ubicacion'),
        ),
        migrations.AddField(
            model_name='movimientocomponente',
            name='origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origen_componente', to='inventario.ubicacion'),
        ),
        migrations.AddField(
            model_name='movimientocomponente',
            name='user_deleted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientocomponente_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por'),
        ),
        migrations.AddField(
            model_name='movimientocomponente',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientocomponente_user_made', to=settings.AUTH_USER_MODEL, verbose_name='hecho por'),
        ),
        migrations.AddField(
            model_name='movimientocomponente',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientocomponente_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddField(
            model_name='impresora',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.ubicacion'),
        ),
        migrations.AddField(
            model_name='impresora',
            name='user_deleted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impresora_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por'),
        ),
        migrations.AddField(
            model_name='impresora',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impresora_user_made', to=settings.AUTH_USER_MODEL, verbose_name='hecho por'),
        ),
        migrations.AddField(
            model_name='impresora',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impresora_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddField(
            model_name='componente',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.terminal'),
        ),
        migrations.AddField(
            model_name='componente',
            name='user_deleted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componente_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por'),
        ),
        migrations.AddField(
            model_name='componente',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componente_user_made', to=settings.AUTH_USER_MODEL, verbose_name='hecho por'),
        ),
        migrations.AddField(
            model_name='componente',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componente_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
    ]
