# Generated by Django 3.2.25 on 2025-06-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='modelo',
        ),
        migrations.AlterField(
            model_name='terminal',
            name='estado',
            field=models.CharField(choices=[('BUENA', 'Buena'), ('NUEVA', 'Nueva'), ('DEFECTUOSA', 'Defectuosa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='mac',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
