# Generated by Django 3.2.25 on 2025-07-01 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0003_auto_20250630_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('hostname', models.CharField(max_length=100)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('mac', models.CharField(blank=True, max_length=17)),
                ('sistema_operativo', models.CharField(max_length=100)),
                ('version_so', models.CharField(max_length=50)),
                ('rol_principal', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('PERFECTO', 'Perfecto'), ('DEFECTUOSO', 'Defectuoso')], max_length=20)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('ultima_revision', models.DateField(blank=True, null=True)),
                ('max_ram', models.IntegerField(null=True)),
                ('max_disco', models.IntegerField(null=True)),
                ('cantidad_puertos', models.IntegerField(null=True)),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.ubicacion')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servidor_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servidor_user_made', to=settings.AUTH_USER_MODEL, verbose_name='hecho por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servidor_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
