# Generated by Django 3.2.25 on 2025-07-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_dispositivoperiferico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Impresora',
        ),
    ]
