# Generated by Django 3.2.25 on 2025-07-04 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0006_auto_20250703_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componentes', to='inventario.terminal'),
        ),
        migrations.CreateModel(
            name='ComponenteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('RAM', 'Memoria RAM'), ('DISCO', 'Disco'), ('MOTHERBOARD', 'Placa Madre'), ('TECLADO', 'Teclado'), ('MONITOR', 'Monitor'), ('MOUSE', 'Mouse'), ('CPU', 'CPU'), ('ROUTER', 'Router'), ('SWITCH', 'Switch'), ('AP', 'Access Point'), ('VGA', 'Cable VGA'), ('HDMI', 'Cable HDMI'), ('ETHERNET', 'Cable Red'), ('OTRO', 'Otro')], max_length=20)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('nro_serie', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=1, null=True)),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componentestock_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componentestock_user_made', to=settings.AUTH_USER_MODEL, verbose_name='hecho por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componentestock_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
