# Generated by Django 3.2.25 on 2025-07-15 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20250704_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='responsable',
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.sector'),
        ),
    ]
