# Generated by Django 3.2.25 on 2025-11-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20250715_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='nombre_descriptivo',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
