# Generated by Django 3.2.25 on 2025-11-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_terminal_nombre_descriptivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='nombre_descriptivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
