# Generated by Django 3.2.25 on 2026-01-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0002_listadoosuthgra'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadoosuthgra',
            name='nombre',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
