# Generated by Django 3.2.25 on 2026-03-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0003_listadoosuthgra_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListadoOsuthgra',
        ),
    ]
